version: '3.9'
services:
      db:
        image: mysql
        ports:
          - 3306
        volumes:
          - myvol:/var/lib/sql
        networks:
          - mynet
        environment:
          - MYSQL_ROOT_PASSWORD=Sid@24
          - MYSQL_DATABASE=wpdb
      
      website:
        image: wordpress
        ports:
          - 80:80
        networks:
          - mynet
        environment:
          - WORDPRESS_DB_HOST=db
          - WORDPRESS_DB_USER=root
          - WORDPRESS_DB_PASSWORD=Sid@24
          - WORDPRESS_DB_NAME=wpdb

networks:
  mynet:
      driver: bridge
volumes:
   myvol:
