version: '3.9'
services:
      web:
        build:
          context: ./web
        ports:
          - 80:80
        volumes:
          - ./web/myhtml:/usr/share/nginx/html/
        networks:
          - webnet
      
      app:
        build:
          context: ./app
        
        ports:
          -9000
        volumes:
          - ./app/myphp:/usr/share/nginx/html/
        networks:
          - webnet
          - phpnet

      db:
        image:
          context: ./db
        ports:
          -3306
        volumes:
          - databac:/var/lib/sql/
        networks:
          - appnet

networks:
  webnet:
    driver: bridge
  appnet:
    driver: bridge

volumes:
  myhtml:
  myphp:
  databac:
